version: "2"

run:
  timeout: 5m
  tests: true
  allow-parallel-runners: true

linters:
  enable:
    - govet
    - staticcheck
    - unused
    - ineffassign
    - misspell
    - revive
  disable:
    - errcheck # Needed

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: "_test\\.go"
      linters:
        - errcheck
        - revive
        - staticcheck
    - text: "var-naming: avoid meaningless package names"
      linters:
        - revive
