# golangci-lint configuration for idmlbuild project
# This configuration balances code quality with existing codebase compatibility

version: 2

run:
  timeout: 10m
  tests: true
  go: "1.23"

# Enable essential linters while being permissive for existing code
linters:
  enable:
    # Static analysis (essential)
    - govet         # Go vet (built-in static analyzer)
    
    # Code quality
    - misspell      # Check for misspelled words in comments and strings
  
  disable:
    # Temporarily disabled for existing codebase - can be enabled incrementally
    - errcheck      # Too many unchecked errors in existing code
    - gosec         # Too many security warnings in test code
    - ineffassign   # Can be enabled after cleanup
    - unused        # Can be enabled after cleanup
    - staticcheck   # Too many style suggestions for existing code

# Configure specific linter settings
linters-settings:
  # errcheck configuration - be more permissive for existing code
  errcheck:
    check-type-assertions: false  # Don't check type assertions for existing code
    check-blank: false           # Allow _ = assignment for ignored errors
    exclude-functions:
      # Common functions where error checking is often intentionally skipped
      - fmt.Print
      - fmt.Printf
      - fmt.Println
      - fmt.Fprint
      - fmt.Fprintf
      - fmt.Fprintln
      - (*os.File).Close
      - (*bytes.Buffer).Write
      - (*bytes.Buffer).WriteString
      - (*strings.Builder).WriteString
      - xml.EscapeText  # xml.EscapeText doesn't return meaningful errors
      - (*archive/zip.ReadCloser).Close
      - (*archive/zip.File).Close
      - (io.Closer).Close
      - (*encoding/xml.Encoder).Flush
  
  # gosec configuration - exclude common false positives
  gosec:
    excludes:
      - G104  # Audit errors not checked (covered by errcheck)
      - G304  # Allow file path from variable (needed for IDML file processing)
      - G306  # Allow poor file permissions in tests
      - G115  # Integer overflow conversion (common in zip file handling)
      - G601  # Implicit memory aliasing in for loop (common pattern)
  
  # staticcheck configuration
  staticcheck:
    checks: ["all"]

# Issue filtering and exclusions
issues:
  # Maximum issues count per one linter (0 = unlimited)
  max-issues-per-linter: 0
  
  # Maximum count of issues with the same text (0 = unlimited)
  max-same-issues: 0
  
  # Exclude directories from linting
  exclude-dirs:
    - testdata
    - vendor
  
  # Exclude files from linting
  exclude-files:
    - ".*_generated\\.go$"
    - ".*\\.pb\\.go$"
  
  # Exclude specific rules and patterns
  exclude-rules:
    # Allow longer functions and complexity in test files
    - path: _test\.go
      linters:
        - funlen
        - gocyclo
        - errcheck
        - gosec
        - unused
        - staticcheck
    
    # Allow dot imports in test files for testify/assert
    - path: _test\.go
      text: "dot imports"
    
    # Allow long lines in generated files or test data
    - path: testdata/
      linters:
        - lll
    
    # Exclude specific error patterns that are acceptable in this codebase
    - text: "Error return value of .*(Close|Flush|.*printf?|os\\.(Un)?Setenv). is not checked"
      linters:
        - errcheck
    
    # Allow type assertions without error checking in CLI/TUI code
    - path: cmd/
      text: "Error return value is not checked"
      linters:
        - errcheck
    
    # Allow unused functions in specific files (utilities, cache management)
    - text: "is unused"
      path: ".*(_test\\.go|package_cache\\.go|package_io\\.go|testutil_test\\.go)$"
      linters:
        - unused
    
    # Allow struct field naming patterns that don't follow Go conventions for XML tags
    - text: "struct field .* should be"
      linters:
        - revive
    
    # Allow repetitive type names for domain-specific types
    - text: "type name will be used as .* by other packages, and that is repetitive"
      linters:
        - revive
    
    # Allow file operations in internal test utilities
    - path: internal/testutil/
      linters:
        - errcheck
        - gosec
    
    # Allow xml.EscapeText without error checking (it doesn't return meaningful errors)
    - text: "Error return value of `xml.EscapeText` is not checked"
      linters:
        - errcheck
        - gosec
    
    # Exclude staticcheck style suggestions
    - text: "QF1003:"
      linters:
        - staticcheck
    - text: "QF1006:"
      linters:
        - staticcheck
    - text: "QF1008:"
      linters:
        - staticcheck
    - text: "SA9003:"
      linters:
        - staticcheck
    - text: "SA5008:"
      linters:
        - staticcheck

# Output configuration
output:
  formats:
    colored-line-number:
      path: stdout
  print-issued-lines: true
  print-linter-name: true
  sort-results: true
