// Code generated by hand-run script (see docs/FIDELITY.md); the methods delegate
// order-preserving XML handling to pkg/common. Edit the list below to add types.

package resources

import (
	"encoding/xml"

	"github.com/dimelords/idmllib/v3/pkg/common"
)

// UnmarshalXML decodes <CellStyle> recording child order (see common.UnmarshalOrdered).
func (x *CellStyle) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	return common.UnmarshalOrdered(x, &x.childOrder, d, start)
}

// MarshalXML encodes <CellStyle> replaying the recorded child order.
func (x CellStyle) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	return common.MarshalOrdered(x, x.childOrder, e, start)
}

// UnmarshalXML decodes <RootCellStyleGroup> recording child order (see common.UnmarshalOrdered).
func (x *CellStyleGroup) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	return common.UnmarshalOrdered(x, &x.childOrder, d, start)
}

// MarshalXML encodes <RootCellStyleGroup> replaying the recorded child order.
func (x CellStyleGroup) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	return common.MarshalOrdered(x, x.childOrder, e, start)
}

// UnmarshalXML decodes <CharacterStyle> recording child order (see common.UnmarshalOrdered).
func (x *CharacterStyle) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	return common.UnmarshalOrdered(x, &x.childOrder, d, start)
}

// MarshalXML encodes <CharacterStyle> replaying the recorded child order.
func (x CharacterStyle) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	return common.MarshalOrdered(x, x.childOrder, e, start)
}

// UnmarshalXML decodes <CompositeFont> recording child order (see common.UnmarshalOrdered).
func (x *CompositeFont) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	return common.UnmarshalOrdered(x, &x.childOrder, d, start)
}

// MarshalXML encodes <CompositeFont> replaying the recorded child order.
func (x CompositeFont) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	return common.MarshalOrdered(x, x.childOrder, e, start)
}

// UnmarshalXML decodes <ObjectStyle> recording child order (see common.UnmarshalOrdered).
func (x *ObjectStyle) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	return common.UnmarshalOrdered(x, &x.childOrder, d, start)
}

// MarshalXML encodes <ObjectStyle> replaying the recorded child order.
func (x ObjectStyle) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	return common.MarshalOrdered(x, x.childOrder, e, start)
}

// UnmarshalXML decodes <ParagraphStyle> recording child order (see common.UnmarshalOrdered).
func (x *ParagraphStyle) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	return common.UnmarshalOrdered(x, &x.childOrder, d, start)
}

// MarshalXML encodes <ParagraphStyle> replaying the recorded child order.
func (x ParagraphStyle) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	return common.MarshalOrdered(x, x.childOrder, e, start)
}

// UnmarshalXML decodes <TableStyle> recording child order (see common.UnmarshalOrdered).
func (x *TableStyle) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	return common.UnmarshalOrdered(x, &x.childOrder, d, start)
}

// MarshalXML encodes <TableStyle> replaying the recorded child order.
func (x TableStyle) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	return common.MarshalOrdered(x, x.childOrder, e, start)
}

// UnmarshalXML decodes <RootTableStyleGroup> recording child order (see common.UnmarshalOrdered).
func (x *TableStyleGroup) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	return common.UnmarshalOrdered(x, &x.childOrder, d, start)
}

// MarshalXML encodes <RootTableStyleGroup> replaying the recorded child order.
func (x TableStyleGroup) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	return common.MarshalOrdered(x, x.childOrder, e, start)
}

// UnmarshalXML decodes an <idPkg:Graphic> file recording child order.
func (x *GraphicFile) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	if start.Name.Local != "Graphic" {
		return common.WrapError("resources", "unmarshal graphic", common.ErrInvalidFormat)
	}
	return common.UnmarshalOrdered(x, &x.childOrder, d, start)
}

// MarshalXML encodes the <idPkg:Graphic> file wrapper replaying the recorded child order.
func (x *GraphicFile) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	wrapper := xml.StartElement{
		Name: xml.Name{Local: "idPkg:Graphic"},
		Attr: []xml.Attr{{Name: xml.Name{Local: "xmlns:idPkg"}, Value: "http://ns.adobe.com/AdobeInDesign/idml/1.0/packaging"}},
	}
	return common.MarshalOrdered(x, x.childOrder, e, wrapper)
}

// UnmarshalXML decodes an <idPkg:Fonts> file recording child order.
func (x *FontsFile) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	if start.Name.Local != "Fonts" {
		return common.WrapError("resources", "unmarshal fonts", common.ErrInvalidFormat)
	}
	return common.UnmarshalOrdered(x, &x.childOrder, d, start)
}

// MarshalXML encodes the <idPkg:Fonts> file wrapper replaying the recorded child order.
func (x *FontsFile) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	wrapper := xml.StartElement{
		Name: xml.Name{Local: "idPkg:Fonts"},
		Attr: []xml.Attr{{Name: xml.Name{Local: "xmlns:idPkg"}, Value: "http://ns.adobe.com/AdobeInDesign/idml/1.0/packaging"}},
	}
	return common.MarshalOrdered(x, x.childOrder, e, wrapper)
}
