// Code generated by hand-run script (see docs/FIDELITY.md); the methods delegate
// order-preserving XML handling to pkg/common. Edit the list below to add types.

package common

import (
	"encoding/xml"
)

// UnmarshalXML decodes <GridDataInformation> recording child order (see common.UnmarshalOrdered).
func (x *GridDataInformation) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	return UnmarshalOrdered(x, &x.childOrder, d, start)
}

// MarshalXML encodes <GridDataInformation> replaying the recorded child order.
func (x GridDataInformation) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	return MarshalOrdered(x, x.childOrder, e, start)
}

// UnmarshalXML decodes <ObjectExportOption> recording child order (see UnmarshalOrdered).
func (x *ObjectExportOption) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	return UnmarshalOrdered(x, &x.childOrder, d, start)
}

// MarshalXML encodes <ObjectExportOption> replaying the recorded child order.
func (x ObjectExportOption) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	return MarshalOrdered(x, x.childOrder, e, start)
}
