// Code generated by hand-run script (see docs/FIDELITY.md); the methods delegate
// order-preserving XML handling to pkg/common. Edit the list below to add types.

package story

import (
	"encoding/xml"

	"github.com/dimelords/idmllib/v3/pkg/common"
)

// UnmarshalXML decodes <XMLElement> recording child order (see common.UnmarshalOrdered).
func (x *XMLElement) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	return common.UnmarshalOrdered(x, &x.childOrder, d, start)
}

// MarshalXML encodes <XMLElement> replaying the recorded child order.
func (x XMLElement) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	return common.MarshalOrdered(x, x.childOrder, e, start)
}

// UnmarshalXML decodes <Change> recording child order (see common.UnmarshalOrdered).
func (x *Change) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	return common.UnmarshalOrdered(x, &x.childOrder, d, start)
}

// MarshalXML encodes <Change> replaying the recorded child order.
func (x Change) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	return common.MarshalOrdered(x, x.childOrder, e, start)
}

// UnmarshalXML decodes <Note> recording child order (see common.UnmarshalOrdered).
func (x *Note) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	return common.UnmarshalOrdered(x, &x.childOrder, d, start)
}

// MarshalXML encodes <Note> replaying the recorded child order.
func (x Note) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	return common.MarshalOrdered(x, x.childOrder, e, start)
}

// UnmarshalXML decodes <HyperlinkTextSource> recording child order (see common.UnmarshalOrdered).
func (x *HyperlinkTextSource) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	return common.UnmarshalOrdered(x, &x.childOrder, d, start)
}

// MarshalXML encodes <HyperlinkTextSource> replaying the recorded child order.
func (x HyperlinkTextSource) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	return common.MarshalOrdered(x, x.childOrder, e, start)
}

// UnmarshalXML decodes <Footnote> recording child order (see common.UnmarshalOrdered).
func (x *Footnote) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	return common.UnmarshalOrdered(x, &x.childOrder, d, start)
}

// MarshalXML encodes <Footnote> replaying the recorded child order.
func (x Footnote) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	return common.MarshalOrdered(x, x.childOrder, e, start)
}

// UnmarshalXML decodes <Table> recording child order (see common.UnmarshalOrdered).
func (x *Table) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	return common.UnmarshalOrdered(x, &x.childOrder, d, start)
}

// MarshalXML encodes <Table> replaying the recorded child order.
func (x Table) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	return common.MarshalOrdered(x, x.childOrder, e, start)
}

// UnmarshalXML decodes <Row> recording child order (see common.UnmarshalOrdered).
func (x *Row) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	return common.UnmarshalOrdered(x, &x.childOrder, d, start)
}

// MarshalXML encodes <Row> replaying the recorded child order.
func (x Row) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	return common.MarshalOrdered(x, x.childOrder, e, start)
}

// UnmarshalXML decodes <Column> recording child order (see common.UnmarshalOrdered).
func (x *Column) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	return common.UnmarshalOrdered(x, &x.childOrder, d, start)
}

// MarshalXML encodes <Column> replaying the recorded child order.
func (x Column) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	return common.MarshalOrdered(x, x.childOrder, e, start)
}

// UnmarshalXML decodes <Cell> recording child order (see common.UnmarshalOrdered).
func (x *Cell) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	return common.UnmarshalOrdered(x, &x.childOrder, d, start)
}

// MarshalXML encodes <Cell> replaying the recorded child order.
func (x Cell) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	return common.MarshalOrdered(x, x.childOrder, e, start)
}
