// Code generated by hand-run script (see docs/FIDELITY.md); the methods delegate
// order-preserving XML handling to pkg/common. Edit the list below to add types.

package spread

import (
	"encoding/xml"

	"github.com/dimelords/idmllib/v2/pkg/common"
)

// UnmarshalXML decodes <GraphicLine> recording child order (see common.UnmarshalOrdered).
func (x *GraphicLine) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	return common.UnmarshalOrdered(x, &x.childOrder, d, start)
}

// MarshalXML encodes <GraphicLine> replaying the recorded child order.
func (x GraphicLine) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	return common.MarshalOrdered(x, x.childOrder, e, start)
}

// UnmarshalXML decodes <Image> recording child order (see common.UnmarshalOrdered).
func (x *Image) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	return common.UnmarshalOrdered(x, &x.childOrder, d, start)
}

// MarshalXML encodes <Image> replaying the recorded child order.
func (x Image) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	return common.MarshalOrdered(x, x.childOrder, e, start)
}

// UnmarshalXML decodes <Oval> recording child order (see common.UnmarshalOrdered).
func (x *Oval) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	return common.UnmarshalOrdered(x, &x.childOrder, d, start)
}

// MarshalXML encodes <Oval> replaying the recorded child order.
func (x Oval) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	return common.MarshalOrdered(x, x.childOrder, e, start)
}

// UnmarshalXML decodes <PDF> recording child order (see common.UnmarshalOrdered).
func (x *PDF) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	return common.UnmarshalOrdered(x, &x.childOrder, d, start)
}

// MarshalXML encodes <PDF> replaying the recorded child order.
func (x PDF) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	return common.MarshalOrdered(x, x.childOrder, e, start)
}

// UnmarshalXML decodes <Page> recording child order (see common.UnmarshalOrdered).
func (x *Page) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	return common.UnmarshalOrdered(x, &x.childOrder, d, start)
}

// MarshalXML encodes <Page> replaying the recorded child order.
func (x Page) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	return common.MarshalOrdered(x, x.childOrder, e, start)
}

// UnmarshalXML decodes <Polygon> recording child order (see common.UnmarshalOrdered).
func (x *Polygon) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	return common.UnmarshalOrdered(x, &x.childOrder, d, start)
}

// MarshalXML encodes <Polygon> replaying the recorded child order.
func (x Polygon) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	return common.MarshalOrdered(x, x.childOrder, e, start)
}

// UnmarshalXML decodes <Rectangle> recording child order (see common.UnmarshalOrdered).
func (x *Rectangle) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	return common.UnmarshalOrdered(x, &x.childOrder, d, start)
}

// MarshalXML encodes <Rectangle> replaying the recorded child order.
func (x Rectangle) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	return common.MarshalOrdered(x, x.childOrder, e, start)
}

// UnmarshalXML decodes <TextFrame> recording child order (see common.UnmarshalOrdered).
func (x *TextFrame) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	return common.UnmarshalOrdered(x, &x.childOrder, d, start)
}

// MarshalXML encodes <TextFrame> replaying the recorded child order.
func (x TextFrame) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	return common.MarshalOrdered(x, x.childOrder, e, start)
}

// UnmarshalXML decodes <TextWrapPreference> recording child order (see common.UnmarshalOrdered).
func (x *TextWrapPreference) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	return common.UnmarshalOrdered(x, &x.childOrder, d, start)
}

// MarshalXML encodes <TextWrapPreference> replaying the recorded child order.
func (x TextWrapPreference) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	return common.MarshalOrdered(x, x.childOrder, e, start)
}

// UnmarshalXML decodes <Group> recording child order (see common.UnmarshalOrdered).
func (x *Group) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	return common.UnmarshalOrdered(x, &x.childOrder, d, start)
}

// MarshalXML encodes <Group> replaying the recorded child order.
func (x Group) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	return common.MarshalOrdered(x, x.childOrder, e, start)
}

// UnmarshalXML decodes <Button> recording child order (see common.UnmarshalOrdered).
func (x *Button) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	return common.UnmarshalOrdered(x, &x.childOrder, d, start)
}

// MarshalXML encodes <Button> replaying the recorded child order.
func (x Button) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	return common.MarshalOrdered(x, x.childOrder, e, start)
}

// UnmarshalXML decodes <State> recording child order (see common.UnmarshalOrdered).
func (x *State) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	return common.UnmarshalOrdered(x, &x.childOrder, d, start)
}

// MarshalXML encodes <State> replaying the recorded child order.
func (x State) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	return common.MarshalOrdered(x, x.childOrder, e, start)
}
