// Code generated by hand-run script (see docs/FIDELITY.md); the methods delegate
// order-preserving XML handling to pkg/common. Edit the list below to add types.

package document

import (
	"encoding/xml"

	"github.com/dimelords/idmllib/v2/pkg/common"
)

// UnmarshalXML decodes <ABullet> recording child order (see common.UnmarshalOrdered).
func (x *ABullet) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	return common.UnmarshalOrdered(x, &x.childOrder, d, start)
}

// MarshalXML encodes <ABullet> replaying the recorded child order.
func (x ABullet) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	return common.MarshalOrdered(x, x.childOrder, e, start)
}

// UnmarshalXML decodes <Assignment> recording child order (see common.UnmarshalOrdered).
func (x *Assignment) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	return common.UnmarshalOrdered(x, &x.childOrder, d, start)
}

// MarshalXML encodes <Assignment> replaying the recorded child order.
func (x Assignment) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	return common.MarshalOrdered(x, x.childOrder, e, start)
}

// UnmarshalXML decodes <ColorGroup> recording child order (see common.UnmarshalOrdered).
func (x *ColorGroup) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	return common.UnmarshalOrdered(x, &x.childOrder, d, start)
}

// MarshalXML encodes <ColorGroup> replaying the recorded child order.
func (x ColorGroup) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	return common.MarshalOrdered(x, x.childOrder, e, start)
}

// UnmarshalXML decodes <DocumentUser> recording child order (see common.UnmarshalOrdered).
func (x *DocumentUser) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	return common.UnmarshalOrdered(x, &x.childOrder, d, start)
}

// MarshalXML encodes <DocumentUser> replaying the recorded child order.
func (x DocumentUser) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	return common.MarshalOrdered(x, x.childOrder, e, start)
}

// UnmarshalXML decodes <Layer> recording child order (see common.UnmarshalOrdered).
func (x *Layer) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	return common.UnmarshalOrdered(x, &x.childOrder, d, start)
}

// MarshalXML encodes <Layer> replaying the recorded child order.
func (x Layer) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	return common.MarshalOrdered(x, x.childOrder, e, start)
}

// UnmarshalXML decodes <NamedGrid> recording child order (see common.UnmarshalOrdered).
func (x *NamedGrid) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	return common.UnmarshalOrdered(x, &x.childOrder, d, start)
}

// MarshalXML encodes <NamedGrid> replaying the recorded child order.
func (x NamedGrid) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	return common.MarshalOrdered(x, x.childOrder, e, start)
}

// UnmarshalXML decodes <Section> recording child order (see common.UnmarshalOrdered).
func (x *Section) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	return common.UnmarshalOrdered(x, &x.childOrder, d, start)
}

// MarshalXML encodes <Section> replaying the recorded child order.
func (x Section) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	return common.MarshalOrdered(x, x.childOrder, e, start)
}

// UnmarshalXML decodes <TextVariable> recording child order (see common.UnmarshalOrdered).
func (x *TextVariable) UnmarshalXML(d *xml.Decoder, start xml.StartElement) error {
	return common.UnmarshalOrdered(x, &x.childOrder, d, start)
}

// MarshalXML encodes <TextVariable> replaying the recorded child order.
func (x TextVariable) MarshalXML(e *xml.Encoder, start xml.StartElement) error {
	return common.MarshalOrdered(x, x.childOrder, e, start)
}
